[mypy]
python_version = 3.11
plugins = pydantic.mypy
ignore_missing_imports = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = False
warn_unreachable = True
strict_optional = True

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
