"""Phase 14 — Monitoring Agent and Closed-Loop Feedback Schemas."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4
from pydantic import BaseModel, Field


class AlertSeverity(str, Enum):
    """Severity levels for monitoring events and alerts."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    FATAL = "fatal"


class AnomalyType(str, Enum):
    """Categorization of detected KPI anomalies."""
    CTR_DROP = "ctr_drop"
    CPA_SPIKE = "cpa_spike"
    ROAS_DROP = "roas_drop"
    CONVERSION_DROP = "conversion_drop"
    BOUNCE_SPIKE = "bounce_spike"
    SPEND_SURGE = "spend_surge"
    IMPRESSION_STALL = "impression_stall"


class MonitoringEvent(BaseModel):
    """Mandatory structured event emitted for all monitored telemetry points.
    
    Contains: campaign_id, timestamp, metric, value, expected_value, deviation, severity.
    """
    event_id: str = Field(default_factory=lambda: f"mon-ev-{uuid4().hex[:10]}")
    campaign_id: str = Field(..., description="Target campaign identifier")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO UTC timestamp of the monitoring event",
    )
    metric: str = Field(..., description="Name of the observed metric, e.g. 'ctr', 'cpa', 'roas'")
    value: float = Field(..., description="Actual observed metric value")
    expected_value: float = Field(..., description="Expected baseline or target KPI value")
    deviation: float = Field(..., description="Calculated deviation delta or ratio")
    severity: AlertSeverity = Field(..., description="Severity level of the event")
    anomaly_type: Optional[AnomalyType] = Field(default=None, description="Classified anomaly type if anomalous")
    description: str = Field(default="", description="Human-readable event description")
    target_agent: Optional[str] = Field(default=None, description="Responsible upstream agent for feedback")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context metadata")


class RawTelemetryPoint(BaseModel):
    """Raw telemetry observation ingested from an ad network or stream."""
    campaign_id: str
    channel: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    impressions: int = Field(default=0, ge=0)
    clicks: int = Field(default=0, ge=0)
    spend: float = Field(default=0.0, ge=0.0)
    conversions: int = Field(default=0, ge=0)
    revenue: float = Field(default=0.0, ge=0.0)
    bounces: int = Field(default=0, ge=0)


class PerformanceSnapshot(BaseModel):
    """Standardized normalized performance snapshot for a specific evaluation interval."""
    snapshot_id: str = Field(default_factory=lambda: f"snap-{uuid4().hex[:8]}")
    campaign_id: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    impressions: int = 0
    clicks: int = 0
    spend: float = 0.0
    conversions: int = 0
    revenue: float = 0.0
    ctr: float = 0.0
    cpc: float = 0.0
    cpa: float = 0.0
    roas: float = 0.0
    conversion_rate: float = 0.0
    channel_breakdown: Dict[str, Dict[str, float]] = Field(default_factory=dict)


class MonitoringReport(BaseModel):
    """Comprehensive monitoring report generated by MonitoringAgent."""
    campaign_id: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    health_score: float = Field(default=100.0, ge=0.0, le=100.0, description="Composite campaign health score (0-100)")
    stream_status: str = Field(default="nominal", description="'nominal', 'degraded', 'critical'")
    snapshots: List[PerformanceSnapshot] = Field(default_factory=list)
    events: List[MonitoringEvent] = Field(default_factory=list)
    alerts: List[Dict[str, Any]] = Field(default_factory=list)
    goal_deviations: Dict[str, float] = Field(default_factory=dict)
    agent_feedback: Dict[str, List[str]] = Field(default_factory=dict)
    observed_kpis: Dict[str, float] = Field(default_factory=dict)
    summary: str = Field(default="")
